version: '3.8'

services:
  # سرویس اصلی برنامه
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
      - DATABASE_URL=postgresql://user:password@timescaledb:5432/aidb
      - REDIS_URL=redis://redis:6379/0
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - timescaledb
      - redis
      - kafka
    volumes:
      - ./app:/app
    networks:
      - ai_network

  # سرویس پایگاه داده TimescaleDB
  timescaledb:
    image: timescale/timescaledb:latest-pg13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=aidb
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    networks:
      - ai_network

  # سرویس Redis برای کش
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - ai_network

  # سرویس Kafka برای پیام‌رسانی
  kafka:
    image: confluentinc/cp-kafka:7.0.0
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - ai_network

  # سرویس ClickHouse برای تحلیل داده
  clickhouse:
    image: yandex/clickhouse-server:21.8
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - ai_network

  # سرویس Prometheus برای مانیتورینگ
  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    networks:
      - ai_network

  # سرویس Grafana برای داشبورد
  grafana:
    image: grafana/grafana:8.2.2
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - ai_network

volumes:
  timescaledb_data:
  redis_data:
  kafka_data:
  clickhouse_data:
  prometheus_data:
  grafana_data:

networks:
  ai_network:
    driver: bridge